name: ml_platform_env
channels:
  - conda-forge
dependencies:
  - python=3.11.11
  - pip
  - altair=5.5.0
  - matplotlib=3.10.1
  - numpy=1.26.4
  - pandas=2.2.2
  - plotly=6.0.1
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - streamlit=1.44.1
  - tabulate=0.9.0
  - pip:
    - tensorflow<=2.17.0